// <auto-generated />
using System;
using FitCal.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitCal.Persistence.Migrations
{
    [DbContext(typeof(FitCalContext))]
    [Migration("20260123193206_Fourth")]
    partial class Fourth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitCal.Core.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FoodId"));

                    b.Property<double>("Calories")
                        .HasColumnType("double precision");

                    b.Property<double>("Carbs")
                        .HasColumnType("double precision");

                    b.Property<double>("Fats")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerAuthUserId")
                        .HasColumnType("uuid");

                    b.Property<double>("Protein")
                        .HasColumnType("double precision");

                    b.Property<double>("ServingSize")
                        .HasColumnType("double precision");

                    b.Property<string>("ServingUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FoodId");

                    b.HasIndex("OwnerAuthUserId");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("FitCal.Core.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeId"));

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("ServingSize")
                        .HasColumnType("double precision");

                    b.Property<string>("ServingUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UserInformationId")
                        .HasColumnType("integer");

                    b.HasKey("RecipeId");

                    b.HasIndex("UserInformationId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("FitCal.Core.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecipeId"));

                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<int>("RecipeId1")
                        .HasColumnType("integer");

                    b.Property<int>("RecipeIngredientId")
                        .HasColumnType("integer");

                    b.HasKey("RecipeId");

                    b.HasIndex("FoodId");

                    b.HasIndex("RecipeId1");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("FitCal.Core.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("UserHistoryId")
                        .HasColumnType("integer");

                    b.Property<int>("UserInformationId")
                        .HasColumnType("integer");

                    b.HasKey("ReportId");

                    b.HasIndex("UserHistoryId");

                    b.HasIndex("UserInformationId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("FitCal.Core.Models.UserHistory", b =>
                {
                    b.Property<int>("UserInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserInformationId"));

                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JournalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("UserHistoryId")
                        .HasColumnType("integer");

                    b.Property<int>("UserInformationId1")
                        .HasColumnType("integer");

                    b.HasKey("UserInformationId");

                    b.HasIndex("FoodId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserInformationId1");

                    b.ToTable("UserHistories");
                });

            modelBuilder.Entity("FitCal.Core.Models.UserInformation", b =>
                {
                    b.Property<int>("UserInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserInformationId"));

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AuthUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Carbs")
                        .HasColumnType("double precision");

                    b.Property<double>("DailyCalories")
                        .HasColumnType("double precision");

                    b.Property<double>("Fats")
                        .HasColumnType("double precision");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<double>("Protein")
                        .HasColumnType("double precision");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.Property<double>("WeightGoal")
                        .HasColumnType("double precision");

                    b.HasKey("UserInformationId");

                    b.HasIndex("AuthUserId")
                        .IsUnique();

                    b.ToTable("UserInformations");
                });

            modelBuilder.Entity("FitCal.Core.Models.Recipe", b =>
                {
                    b.HasOne("FitCal.Core.Models.UserInformation", "UserInformation")
                        .WithMany("Recipes")
                        .HasForeignKey("UserInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInformation");
                });

            modelBuilder.Entity("FitCal.Core.Models.RecipeIngredient", b =>
                {
                    b.HasOne("FitCal.Core.Models.Food", "Food")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitCal.Core.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("FitCal.Core.Models.Report", b =>
                {
                    b.HasOne("FitCal.Core.Models.UserHistory", "UserHistory")
                        .WithMany()
                        .HasForeignKey("UserHistoryId");

                    b.HasOne("FitCal.Core.Models.UserInformation", "UserInformation")
                        .WithMany("Reports")
                        .HasForeignKey("UserInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserHistory");

                    b.Navigation("UserInformation");
                });

            modelBuilder.Entity("FitCal.Core.Models.UserHistory", b =>
                {
                    b.HasOne("FitCal.Core.Models.Food", "Food")
                        .WithMany("UserHistories")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitCal.Core.Models.Recipe", null)
                        .WithMany("UserHistories")
                        .HasForeignKey("RecipeId");

                    b.HasOne("FitCal.Core.Models.UserInformation", "UserInformation")
                        .WithMany("UserHistories")
                        .HasForeignKey("UserInformationId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("UserInformation");
                });

            modelBuilder.Entity("FitCal.Core.Models.Food", b =>
                {
                    b.Navigation("RecipeIngredients");

                    b.Navigation("UserHistories");
                });

            modelBuilder.Entity("FitCal.Core.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");

                    b.Navigation("UserHistories");
                });

            modelBuilder.Entity("FitCal.Core.Models.UserInformation", b =>
                {
                    b.Navigation("Recipes");

                    b.Navigation("Reports");

                    b.Navigation("UserHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
